apiVersion: apps/v1
kind: Deployment
metadata:
  name: rundeck-deployment
  namespace: rundeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rundeck
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      containers:
      - name: rundeck
        image: rundeck/rundeck:5.2.0
        ports:
        - containerPort: 80
        - containerPort: 4440
        env:
        - name: JVM_MAX_RAM_PERCENTAGE
          value: "50"
        # - name: RUNDECK_SERVER_UUID
        #   value: "unique-server-uuid"
        - name: RUNDECK_GRAILS_URL
          value: "yoursite.com.br"
        - name: RUNDECK_SERVER_FORWARDED
          value: "false"
