apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  # csi:
  #   driver: blockvolume.csi.oraclecloud.com
  #   volumeHandle: ocid1.volume.oc1....
  hostPath:
    path: /etc/gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  # csi:
  #   driver: blockvolume.csi.oraclecloud.com
  #   volumeHandle: ocid1.volume.oc1....
  hostPath:
    path: /var/opt/gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi