apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret-bookstack
  namespace: bookstack
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: help-ic-secrets
  data:
  - secretKey: SAML2_IDP_x509
    remoteRef:
      key: help-ic-secrets
      property: SAML2_IDP_x509
  - secretKey: APP_URL
    remoteRef:
      key: help-ic-secrets
      property: APP_URL
  - secretKey: DB_PASS
    remoteRef:
      key: help-ic-secrets
      property: DB_PASS
  - secretKey: DB_USER
    remoteRef:
      key: help-ic-secrets
      property: DB_USER
  - secretKey: MAIL_PASSWORD
    remoteRef:
      key: help-ic-secrets
      property: MAIL_PASSWORD
  - secretKey: MAIL_USERNAME
    remoteRef:
      key: help-ic-secrets
      property: MAIL_USERNAME

