apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
      - name: bookstack
        image: linuxserver/bookstack
        ports:
        - containerPort: 80

        # Dados sensíveis abstraídos com o uso do Hashicorp Vault
        envFrom:
        - secretRef:
            name: help-ic-secrets

        # Variáveis de ambiente | BD
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "986"
        - name: DB_HOST
          value: "bookstackdb"
        - name: DB_DATABASE
          value: "bookstack"

        # Noreply
        - name: MAIL_DRIVER
          value: smtp
        - name: MAIL_FROM_NAME
          value: noreply
        - name: MAIL_FROM
          value: noreply@yoursite.com.br
        - name: MAIL_HOST
          value: smtp.office365.com
        - name: MAIL_PORT
          value: '587'
        - name: MAIL_ENCRYPTION
          value: TLS

        # SAML 2.0 Authentication
        - name: AUTH_METHOD
          value: saml2
        - name: AUTH_AUTO_INITIATE
          value: 'false'
        - name: SAML2_NAME
          value: SSO
        - name: SAML2_EMAIL_ATTRIBUTE
          value: email
        - name: SAML2_EXTERNAL_ID_ATTRIBUTE
          value: uid
        - name: SAML2_DISPLAY_NAME_ATTRIBUTES
          value: username
        - name: SAML2_IDP_ENTITYID
          value: https://sts.windows.net/your.id/
        - name: SAML2_AUTOLOAD_METADATA
          value: 'false'
        - name: SAML2_IDP_SSO
          value: https://login.microsoftonline.com/your.id/saml2
        - name: SAML2_IDP_SLO
          value: https://login.microsoftonline.com/your.id/saml2
        - name: SAML2_IDP_AUTHNCONTEXT
          value: 'true'
        
        volumeMounts:
        - mountPath: "/config"
          name: bokstackvolume
      volumes:
      - name: bokstackvolume
        persistentVolumeClaim:
          claimName: bookstackpvc