apiVersion: v1
kind: PersistentVolume
metadata:
  name: bookstackpv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi #ajuste conforme sua necessidade
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/bookstack"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstackpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi #ajuste conforme sua necessidade