apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret-bookstack
  namespace: bookstack
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: [secrets-path-name]
  data:
  - secretKey: [secret-name]
    remoteRef:
      key: [secrets-path-name]
      property: [secret-name]

