apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab-container
        image: gitlab/gitlab-ce:16.11.0-ce.0
        # resources:
        #   requests:
        #     memory: "2Gi"
        #     cpu: "1"
        #   limits:
        #     memory: "6Gi"
        #     cpu: "2"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            # DB config
            external_url 'http://yoursite.com.br'
            gitlab_rails['db_adapter'] = "postgresql"
            gitlab_rails['db_encoding'] = "unicode"
            gitlab_rails['db_host'] = "postgres-svc"
            gitlab_rails['db_port'] = "5432"
            gitlab_rails['db_username'] = "postgres"
            gitlab_rails['db_password'] = "your pwd" # use a external secrets or something to better!
            redis['enable'] = false
            gitlab_rails['redis_host'] = "redis-svc"
            gitlab_rails['redis_port'] = "6379"

            # SMTP (example)
            gitlab_rails['gitlab_email_enabled'] = true
            gitlab_rails['gitlab_email_from'] = 'noreply@yoursite.com.br'
            gitlab_rails['gitlab_email_display_name'] = 'GitLab No Reply'
            gitlab_rails['gitlab_email_reply_to'] = 'noreply@yoursite.com.br'
            gitlab_rails['smtp_enable'] = true
            gitlab_rails['smtp_address'] = 'smtp.office365.com'
            gitlab_rails['smtp_port'] = 587
            gitlab_rails['smtp_user_name'] = 'noreply@yoursite.com.br'
            gitlab_rails['smtp_password'] = 'Your SMTP pwd'
            gitlab_rails['smtp_domain'] = 'yoursite.com.br'
            gitlab_rails['smtp_authentication'] = 'login'
            gitlab_rails['smtp_enable_starttls_auto'] = true
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oci-bv
  hostPath:
    path: /etc/gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oci-bv
  hostPath:
    path: /var/opt/gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gitlab
  namespace: gitlab
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - git.inventcloud.com.br
    secretName: gitlab-tls
  rules:
  - host: git.inventcloud.com.br
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gitlab-svc
              port:
                number: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-postgres
  namespace: gitlab
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: gitlabhq_production
        - name: POSTGRES_PASSWORD
          value: j7xNSP29iFAxURCbkGHX
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: gitlab
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-redis
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:latest # redis:7.0.15-alpine3.20
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: gitlab
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
