apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab-container
        image: gitlab/gitlab-ce:16.11.0-ce.0
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'http://yoursite.com.br'
            gitlab_rails['db_adapter'] = "postgresql"
            gitlab_rails['db_encoding'] = "unicode"
            gitlab_rails['db_host'] = "postgres-svc"
            gitlab_rails['db_port'] = "5432"
            gitlab_rails['db_username'] = "postgres"
            gitlab_rails['db_password'] = "your pwd" # use a external secrets or something to better!
            redis['enable'] = false
            gitlab_rails['redis_host'] = "redis-svc"
            gitlab_rails['redis_port'] = "6379"
            gitlab_rails['gitlab_email_enabled'] = true
            gitlab_rails['gitlab_email_from'] = 'noreply@yoursite.com.br'
            gitlab_rails['gitlab_email_display_name'] = 'GitLab No Reply'
            gitlab_rails['gitlab_email_reply_to'] = 'noreply@yoursite.com.br'
            gitlab_rails['smtp_enable'] = true
            gitlab_rails['smtp_address'] = 'smtp.office365.com'
            gitlab_rails['smtp_port'] = 587
            gitlab_rails['smtp_user_name'] = 'noreply@yoursite.com.br'
            gitlab_rails['smtp_password'] = 'Your SMTP pwd'
            gitlab_rails['smtp_domain'] = 'yoursite.com.br'
            gitlab_rails['smtp_authentication'] = 'login'
            gitlab_rails['smtp_enable_starttls_auto'] = true
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config-pvc

---

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: oci-bv
  hostPath:
    path: /path/to/host/directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv
